### ISSUE TITLE
returned a non-zero code: 137

### ISSUE THREAD

**Issue by rgaiacs** [conda-forge/quarto-feedstock#17] opened 2023-05-30 15:03 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi, I'm trying to install quarto using conda in a container and I'm getting a returned a non-zero code: 137. Any help?

```
Step 48/48 : RUN conda install -y -n notebook --channel conda-forge quarto
 ---> Running in c2150f68d5eb
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... Killed
Removing intermediate container c2150f68d5eb
The command '/bin/sh -c conda install -y -n notebook --channel conda-forge quarto' returned a non-zero code: 137
```

### Installed packages

```shell
quarto
```

### Environment info

```shell
Using from `repo2docker` with

repo2docker \
    --no-run \
    --user-name methodshub \
    --image-name methodshub/gesis-methods-hub/minimal-example-ipynb-python:04e54913cb1a81d52c0dd8e7ece7c4a1668d6648 \
    --appendix 'RUN conda install -y -n notebook --channel conda-forge quarto' \
    https://github.com/GESIS-Methods-Hub/minimal-example-ipynb-python.git
```

**Comment by mfisher87** [comment] 2023-05-31 04:51
I've not been able to reproduce this with the command from the end of your post. I get a working JupyterLab instance with a working Quarto package. I'm not sure what to suggest the cause of your error is, but I don't think it's the conda package. I'm particularly interested in why it says `Killed`. Do you have enough memory to solve the environment? That's my current top suspect.

Also, I would suggest to try using the [`environment.yml`](https://repo2docker.readthedocs.io/en/latest/config_files.html#environment-yml-install-a-conda-environment) configuration file instead of the `--appendix` argument to define a repo2docker conda environment. [Here](https://github.com/CryoInTheCloud/hub-image/blob/main/environment.yml) is an example from a project I recently worked on. 

At this point I think this repository is probably not the cause of your problem, so I'm closing the issue. Feel free to re-open if you think otherwise.

**Closed by mfisher87** 2023-05-31 04:51 UTC
Labels: bug

**Comment by rgaiacs** [comment] 2023-05-31 06:42
Hi @mfisher87,

Thanks for the message.

When I run today, I couldn't reproduce the error. Instead, I got a successful build with

```
Step 49/49 : RUN conda install -y -n notebook --channel conda-forge quarto
 ---> Running in fd1ab58004a1
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.13.0
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/conda/envs/notebook

  added / updated specs:
    - quarto


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    certifi-2023.5.7           |     pyhd8ed1ab_0         149 KB  conda-forge
    dart-sass-1.58.3           |       ha770c72_1         2.8 MB  conda-forge
    deno-1.28.2                |       h2f28480_0        28.1 MB  conda-forge
    deno-dom-0.1.35            |       hd9586b0_1         1.0 MB  conda-forge
    esbuild-0.15.5             |       ha770c72_1         3.2 MB  conda-forge
    libzlib-1.2.13             |       h166bdaf_4          64 KB  conda-forge
    openssl-1.1.1u             |       hd590300_0         1.9 MB  conda-forge
    pandoc-3.1.1               |       h32600fe_0        26.2 MB  conda-forge
    quarto-1.3.340             |       ha770c72_0        12.2 MB  conda-forge
    zlib-1.2.13                |       h166bdaf_4          92 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        75.8 MB

The following NEW packages will be INSTALLED:

  dart-sass          conda-forge/linux-64::dart-sass-1.58.3-ha770c72_1
  deno               conda-forge/linux-64::deno-1.28.2-h2f28480_0
  deno-dom           conda-forge/linux-64::deno-dom-0.1.35-hd9586b0_1
  esbuild            conda-forge/linux-64::esbuild-0.15.5-ha770c72_1
  quarto             conda-forge/linux-64::quarto-1.3.340-ha770c72_0

The following packages will be UPDATED:

  ca-certificates                      2022.9.24-ha878542_0 --> 2023.5.7-hbcca054_0
  certifi                            2022.9.24-pyhd8ed1ab_0 --> 2023.5.7-pyhd8ed1ab_0
  libzlib                                 1.2.12-h166bdaf_4 --> 1.2.13-h166bdaf_4
  openssl                                 1.1.1q-h166bdaf_0 --> 1.1.1u-hd590300_0
  pandoc                                  2.19.2-ha770c72_0 --> 3.1.1-h32600fe_0
  zlib                                    1.2.12-h166bdaf_4 --> 1.2.13-h166bdaf_4



Downloading and Extracting Packages
zlib-1.2.13          | 92 KB     | ########## | 100% 
openssl-1.1.1u       | 1.9 MB    | ########## | 100% 
pandoc-3.1.1         | 26.2 MB   | ########## | 100% 
certifi-2023.5.7     | 149 KB    | ########## | 100% 
dart-sass-1.58.3     | 2.8 MB    | ########## | 100% 
libzlib-1.2.13       | 64 KB     | ########## | 100% 
deno-dom-0.1.35      | 1.0 MB    | ########## | 100% 
esbuild-0.15.5       | 3.2 MB    | ########## | 100% 
quarto-1.3.340       | 12.2 MB   | ########## | 100% 
deno-1.28.2          | 28.1 MB   | ########## | 100% 
ca-certificates-2023 | 145 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Removing intermediate container fd1ab58004a1
 ---> 3ac0d7fd0b0c
{"aux": {"ID": "sha256:3ac0d7fd0b0c628322ab9e4c4c50ca644be7f28c9f1889a7c8cac73a0c33847f"}}Successfully built 3ac0d7fd0b0c
Successfully tagged methodshub/gesis-methods-hub/minimal-example-ipynb-python:04e54913cb1a81d52c0dd8e7ece7c4a1668d6648
```

For some reason, yesterday the `current_repodata.json` was not resolving. Thanks for the support.

**Comment by mfisher87** [comment] 2023-05-31 13:56
Glad it worked out :)
